version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8080:8080
      - 6006:6006
    volumes:
      - ../..:/workspaces:cached
      - ~/Documents/datasets/tflogs/logs/:/mnt/logs
    command: sleep infinity
